<a href="https://colab.research.google.com/github/SunnyDahitJ/NNDL/blob/main/NNDL_practial_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy.core.numeric import identity
import numpy as np

#default data type for ones matrix is float
n_ones =  np.ones((4,4), dtype = int)

print(n_ones)

n_identity = np.identity(3, dtype=int)

print(n_identity)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
